name: Delhiiloveyou
favicon: null
layout_spectrum: 0.99294
typography_spectrum: 0.5151125760748982
title: 'Delhi, I Love You'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4008f'
    - '#ff80d1'
    - '#c2c31b'
    - '#008e93'
    - '#00ff00'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.07658969354815781
purpose: []
